spring:
  application:
    name: neogedom-config-server
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

greeting-service: 
  greeting: "Olá"
  default-value: "Mundo"

